Miol-Mor/battle-game

.github/workflows/rust.yml, backend/src/main.rs
Run linter, then run build and tests
=> Add actions rust workflow

backend/Cargo.toml, backend/src/main.rs, backend/src/socket.rs
WIP: create socket that accepts connections on 9001 port
But there is couple of things to discuss and fix
#4
=> Echo socket

frontend/game.js, frontend/grid.js
* Move Hex_grid graphic constants inside class
* Now background color - Game graphic constant
* Add draw_hex function for debug
=> !hotfix: Show grid correctly.

backend/src/game.rs, backend/src/game_objects/grid.rs, backend/src/main.rs, backend/src/websocket.rs
#30
Every user will receive field on connection by websocket
Now it looks like this: 
`{"row_n":2,"col_n":2,"field":{"hexes":[{"x":0,"y":0,"unit":null,"content":null},{"x":0,"y":1,"unit":null,"content":null},{"x":1,"y":0,"unit":null,"content":null},{"x":1,"y":1,"unit":null,"content":null}]}}`
=> Send field to everyone who connect to websocket

backend/src/game.rs, backend/src/game_objects/grid.rs, backend/src/game_objects/hex.rs, backend/src/game_objects/unit.rs, backend/src/websocket.rs
=> Change unit field attack -> damage #46

backend/src/appstate.rs, backend/src/communicator.rs, backend/src/main.rs, backend/src/websocket.rs
Add communicator to communicate with clients
#67
=> Add current player

backend/src/api/inner.rs, backend/src/api/mod.rs, backend/src/api/request.rs, backend/src/api/response.rs, backend/src/appstate.rs, backend/src/game.rs, backend/src/handlers/user.rs, backend/src/main.rs, backend/src/models/user.rs, backend/src/websocket.rs
=> Make appstate an actor

frontend/src/game.js
=> Redraw stats on attack and move #85

frontend/src/game.js, frontend/src/unit.js
=> Selected unit now pulsing

.github/workflows/js.yml, backend/src/game.rs, frontend/src/game.js, frontend/tests/grid.test.js
Close #117
* Fix #107
* One letter refactoring
=> Add test check for front to Github Actions #117

frontend/src/game.js
=> Add information about current turn #90

frontend/src/game.js
=> Start new game for each player on reconnection #105

frontend/src/unit.js
=> Another function for unit to pulse

backend/src/game.rs, backend/src/game_server.rs
=> Check if current player select there unit

backend/src/api/response.rs, backend/src/game.rs, backend/src/game_objects/grid.rs, backend/src/game_objects/hex.rs, backend/src/game_server.rs, frontend/src/helpers.js
=> Check if attacking unit is nearby

backend/Cargo.toml, backend/src/game.rs, frontend/src/game.js, frontend/src/helpers.js
Solves #78 
This PR contains backend logic with find path, where player wants to move unit and return it to client or return error if path is not correct. And move unit on frontend
=> Check if unit available to move to given point

backend/src/api/response.rs, backend/src/game.rs, backend/src/game_objects/grid.rs, backend/src/game_objects/hex.rs, backend/src/game_server.rs
=> Check if attacking unit nearby

backend/src/game.rs, backend/src/game_objects/unit.rs, backend/src/game_server.rs
=> Added state function for game and refactoring

backend/src/game.rs, backend/src/game_server.rs
Added `check_action_available` function which checks if user can perform there action
Solves #124
=> Added action check for game_server

backend/src/game_server.rs
=> Reload game when active player leaves game and inactive becomes active

backend/src/game.rs, backend/src/game_server.rs, frontend/src/game.js
=> Unit moves are correct now

backend/src/api/response.rs, backend/src/game_server.rs, frontend/src/game.js
Closes #165
New event 'queue' shows how many players connected to the game
and your position in players queue
Frontend shows you hints if you have to wait for second player
or wait for other players to leave
=>  New queue event and displaying your position in queue

backend/src/api/response.rs, backend/src/game.rs, backend/src/game_objects/grid.rs, backend/src/game_server.rs, frontend/src/game.js
It sends when there are one player on the field left
Frontend shows alert on this event
Closes #81
=> New "end game" event added

backend/src/api/response.rs, backend/src/game.rs, backend/src/game_objects/grid.rs, backend/src/game_objects/hex.rs, backend/src/game_objects/unit.rs, backend/src/game_server.rs, frontend/src/game.js
=> Generate new random game with predifined limits

backend/src/api/request.rs, backend/src/api/response.rs, backend/src/game_server.rs, backend/src/websocket.rs, frontend/src/game.js
Now game could be started with any number of players (>= 2)
* Close #181
* Stop game on one of players disconnect. Close #174
=> Add start game button
